### ISSUE TITLE
[Collection selection] remove ambiguous trashcan symbol, bad button layout

### ISSUE THREAD

**Issue by DavidGretzschel** [supermemo/SuperMemoAssistant#119]
![image](https://user-images.githubusercontent.com/23729465/75168604-75357480-5727-11ea-84a9-dfd91f2a9fea.png)

A trashcan can either mean "remove" or "delete" with "delete" being easily the more salient association. Noone would certainly want to click this button, since it might possibly delete the whole SuperMemo-collection!
There is no point either in not having the two possible actions that you can do on a Collection in this menu be visually seperated.
The trashcan-icon should go away and a "Remove"-button should be put to the left of the "Open"-button.
Then the "Browse" button should be renamed into either "Add Collection" and be positioned more closely next to the "Options"-button, so that the actions that act on an individual collection and those that don't are visually seperated.

**Comment by alexis-** [comment]
Kept the button (as discussed in #sma-ideas, see below), changed the icon to a X with a tool tip.

<hr/>

[Link to message in Discord](https://discordapp.com/channels/673071773700587521/673076360888975363/678949909877227531)

**Alexis.Inco**
All very good. There's only one thing I don't agree with, it is removing the "remove" (the pictogram can change) button in-line with the collection. Adding a single button at the bottom possibly adds an additional click, which is annoying

**David Gretzschel**
well, you click alt first and then the underlined letter, like a civilized person do you not :)
for that matter, it'd be nice to rename "Options" to "Settings", so that can be hit with "s" and there's no conflict with "Open"
but I guess that might seem like an obscure optimization for people not using the letter system in Windows

**Alexis.Inco**
> well, you click alt first and then the underlined letter, like a civilized person do you not :)

@David Gretzschel I also heavily rely on hotkeys, but many users do not know about this. I'd rather keep it very obvious (which is in line with all your suggestions so far)

**Comment by DavidGretzschel** [comment]
Extra click? I suppose.
Well at the moment you can immediately go to "remove" (which is now a red "X") by pressing tab once. "X" is definitely less scary than a "trashcan", though I don't find it obvious either.

If the pictogram was removed and turned into a button to the right of "Options", it would take one less tab to click "Options". So it's a tradeoff.
Both are rare actions, though "Options" is probably rarer.

My intution would be that people who'd handle a lot of collections and want to remove and readd them a lot, would likely prefer using access-keys, anyway.
And also that the same people who'd know/suspect that you can use the tab key to select UI-elements would also know and prefer using access-keys.
